### ISSUE TITLE
Fine-tuning SigLIP

### ISSUE THREAD

**Issue by SeyedAlirezaFatemi** [merveenoyan/siglip#2]
Hi!

Thanks for putting these applications together in the repo. Do you have any advice or good resources on fine-tuning SigLIP on custom data?

**Comment by merveenoyan** [comment]
I think it should be very similar to CLIP fine-tuning for which there's a good blog post here: https://huggingface.co/blog/fine-tune-clip-rsicd

**Comment by SeyedAlirezaFatemi** [comment]
Thanks for the response and reference.🙏
